name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - netcdf4
  - geopandas
  - satpy
  - iris
  - cartopy
  - xesmf
  - climlab
  - obspy
  - eofs
  - holoviews
  - hvplot
  - rasterio
  - gcsfs
  - pip:
    - discretize
